#.travis.yml

language: node_js
node_js:
  - "6.9"

branches:
  only:
    - master

before_script:
  - npm install -g bower
  - npm install -g gulp
  - npm install
  - bower install

script:
  - gulp dev

after_success:
  - 

notifications:
  email:
    on_failure: change
    on_success: change